
service:

  nginx:
    container_name: nginx
  build:
    context: ./requirements/nginx
    dockerfile: Dockerfile
  restart: on-failure
  network:
    - inception



  wordpress:
    container_name: wordpress
  build:
      context: ./requirements/wordpress
      dockerfile: Dockerfile
  restart: on-failure
  network:
    - inception



  mariaDB:
    container_name: mariaDB
  build:
      context: ./requirements/mariadb
      dockerfile: Dockerfile
  restart: on-failure
  network:
    - inception




network:
  inception:
    driver: bridge


      #volumes:
      #db_data
      #wb_file
