
services:

  nginx:
    container_name: nginx
    build:
      context: ./requirements/nginx
      dockerfile: Dockerfile
    restart: on-failure
    ports:
      - "443:443"
    networks:
      - inception
    volumes:
      - wordpress_data:/var/www/html
    depends_on:
      - wordpress



  wordpress:
    container_name: wordpress
    build:
      context: ./requirements/wordpress
      dockerfile: Dockerfile
    restart: on-failure
    depends_on:
      - mariadb
    networks:
      - inception
    volumes:
      - wordpress_data:/var/www/html
    environment:
      WORDPRESS_DB_HOST: mariadb:3306 # esponendo la porta 3306 per collegarlo al db
      WORDPRESS_DB_USER: lde-mich
      WORDPRESS_DB_PASSWORD: root
      WORDPRESS_DB_NAME: mariadb
    depends_on:
      - mariadb



  mariadb:
    container_name: mariadb
    build:
      context: ./requirements/mariadb
      dockerfile: Dockerfile
    restart: on-failure
    ports:
      - "3307:3306"
    networks:
      - inception
    volumes:
      - db_data:/var/lib/mysql



networks:
  inception:
    driver: bridge


volumes:
  db_data:
  wordpress_data:


