
service:

  nginx:
    container_name: nginx
  restart: on-failure
  network:
    - inception



  word-press:
    container_name: word-press
  restart: on-failure
  network:
    - inception



  mariaDB:
    container_name: mariaDB
  restart: on-failure
  network:
    - inception




network:
  inception:
    driver: bridge


volumes:
  db_data
  wb_file
